### ISSUE TITLE
turnip_formatter 0.4.0 対応お願いしたいです m(_ _)m

### ISSUE THREAD

**Issue by kazaoki** [gongo/gnawrnip#22]
turnip_formatter が 0.4.0 に更新したので `bundle update` したのですが turnip_formatter 0.3.4 のままアップデートされず。
おかしーなーと思っていたら、rubygems の方の gnawrnip でバージョン依存してるんですね・・。 

https://rubygems.org/gems/gnawrnip
`turnip_formatter ~> 0.3.2`

turnip_formatter 0.4.0 対応待ってます・・！

**Comment by gongo** [comment]
@kazaoki さんの仰る通り、まだ gnawrnip の方は手をつけていませんでした :bow: 
もうしばしお待ち下さいませ :muscle:

**Comment by kazaoki** [comment]
お早いご返答ありがとうございます・・！
お待ちしております！

**Comment by gongo** [comment]
@kazaoki 

`turnip_formatter 0.4.0` 対応の `gnawrnip 0.4.0` を先程リリースしたのでお試しください :muscle: 
何かおかしいところがあれば、また issue にてよろしくお願い致します。

**Comment by kazaoki** [comment]
ありがとうございました！
無事 `bundler update` から 0.4.0 に更新できました！
いつも助かっています！
